INSERT INTO USER_DETAILS (NAME, ID, BIRTH_DATE) VALUES ('John Doe', 1, '1990-05-15');
INSERT INTO USER_DETAILS (NAME, ID, BIRTH_DATE) VALUES ('John ', 2, '1990-05-25');
INSERT INTO USER_DETAILS (NAME, ID, BIRTH_DATE) VALUES ('John Jack', 3, '1990-05-05');
INSERT INTO POST_DETAILS (ID, DESCRIPTION, USER_ID) VALUES (2001,'I want to learn SPring', 1);
INSERT INTO POST_DETAILS (ID, DESCRIPTION, USER_ID) VALUES (2002,'I want to learn Aws', 2);
INSERT INTO POST_DETAILS (ID, DESCRIPTION, USER_ID) VALUES (2003,'I want to learn Cloud', 3);
